<?php

namespace DoctrineORMModule\Proxy\__CG__\Ponto\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Funcionario extends \Ponto\Entity\Funcionario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __set($property, $value)
    {
        $this->__load();
        return parent::__set($property, $value);
    }

    public function __get($property)
    {
        $this->__load();
        return parent::__get($property);
    }

    public function encryptPassword($senha)
    {
        $this->__load();
        return parent::encryptPassword($senha);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function populate(array $data = array (
))
    {
        $this->__load();
        return parent::populate($data);
    }

    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {
        $this->__load();
        return parent::setInputFilter($inputFilter);
    }

    public function getInputFilter()
    {
        $this->__load();
        return parent::getInputFilter();
    }

    public function setServiceLocator($serviceLocator)
    {
        $this->__load();
        return parent::setServiceLocator($serviceLocator);
    }

    public function getServiceLocator()
    {
        $this->__load();
        return parent::getServiceLocator();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nome', 'email', 'usuario', 'senha', 'status', 'permissao', 'area', 'departamento', 'funcao', 'salt');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}