<?php $urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern) {
    if (!preg_match("/pagina/", $urlPattern))
        return "{$urlPattern}/pagina/{$page}";
    return preg_replace("/\d+/", $page, $urlPattern);
}; ?>

<center>
<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <?php echo $this->firstItemNumber; ?> - 
            <?php echo $this->lastItemNumber; ?> de 
                <?php echo $this->totalItemCount; ?> páginas <br />
        <ul class="pagination">
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $formatUrl($this->first) ?>">Primeira</a></li>
            <?php else: ?>
                <li class="disabled"><span>Primeira</span></li>
            <?php endif; ?>
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $formatUrl($this->previous) ?>">< Anterior</a></li>
            <?php else: ?>
                <li class="disabled"><span>< Anterior</span></li>
            <?php endif; ?>
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->next); ?>">Próximo ></a></li>
            <?php else: ?>
                <li class="disabled"><span>Próximo ></span></li>
            <?php endif; ?>
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->last); ?>">Último</a></li>
            <?php else: ?>
                <li class="disabled"><span>Último</span></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>
</center>