<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
          <div class="container">
            <div class="navbar-header">
              <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a href="<?php echo $this->url("ponto"); ?>" class="navbar-brand">Zend 2</a>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
              <ul class="nav navbar-nav">
                <?php if ($this->UserIdentity("PontoLogin")) :?>
                <?php if ($this->UserIdentity("PontoLogin")->__get("permissao") == \Ponto\Entity\Funcionario::PERMISSAO_ADMIN): ?>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Funcionário <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="<?php echo $this->url("ponto", array(
                        "controller" => "funcionario")); ?>">Listar</a></li>
                      <li><a href="<?php echo $this->url("ponto", array(
                        "controller" => "funcionario", 
                        "action" => "inserir")); ?>">Cadastrar</a></li>
                    </ul>
                </li>
                <?php endif; ?>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lançamento <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="<?php echo $this->url("ponto", array(
                        "controller" => "lancamento")); ?>">Listar</a></li>
                      <li><a href="<?php echo $this->url("ponto", array(
                        "controller" => "lancamento", 
                        "action" => "inserir")); ?>">Cadastrar</a></li>
                    </ul>
                </li>
                <li><a href="<?php echo $this->url("ponto-logout"); ?>">Sair</a></li>
                <?php endif; ?>
              </ul>
            </nav>
          </div>
        </header>
        <div class="container">
            <?php foreach ($this->flashMessages(true) as $namespace => $messages) : ?>
                <?php if (count($messages)) : ?>
                    <?php foreach ($messages as $message) : ?>
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert">X</button>
                        <?php echo $message; ?>
                    </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date("Y"); ?> by Leonard A. Technologies <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
