<?php $this->headTitle('Funcionarios'); ?>

<h1><span class="glyphicon glyphicon-user"></span>&nbsp <?php echo $this->escapeHtml('Funcionários'); ?></h1>

<a href="<?php echo $this->url("ponto", array(
    "controller" => "funcionario", "action" => "inserir")); ?>" 
        class="btn btn-success">Novo</a></br></br>
        
<table class="table table-striped">
<tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Usuario</th>
    <th>E-Mail</th>
    <th>Área</th>
    <th>Função</th>
    <th>Permissão</th>
    <th>Opções</th>
</tr>
<?php foreach ($this->dados as $value) : ?>
<tr>
    <td><?php echo $this->escapeHtml($value->__get("id")); ?></td>
    <td><?php echo $this->escapeHtml($value->__get("nome")); ?></td>
    <td><?php echo $this->escapeHtml($value->__get("usuario")); ?></td>
    <td><?php echo $this->escapeHtml($value->__get("email")); ?></td>
    <td><?php echo $this->escapeHtml($value->__get("area")); ?></td>
    <td><?php echo $this->escapeHtml($value->__get("funcao")); ?></td>
    <td><?php echo $this->escapeHtml($value->__get("permissao")); ?></td>
    <td>
        <a class="btn btn-primary" href="<?php echo $this->url(
            'ponto', array("controller" => "funcionario", "action" => "editar", 
                "id" => $value->__get("id")));?>">Editar</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<?php echo $this->paginationControl($this->dados ,'Sliding','paginator'); ?>
