<h1><span class="glyphicon glyphicon-lock"></span>&nbsp <?php echo $this->escapeHtml('Login'); ?></h1>
<br />

<?php $this->form->setAttribute('action', $this->url(
    "ponto-login", array("controller" => "funcionario","action" => "login"))); ?>

<div class="row">
    <div class="col-md-4">
        <?php $this->form->prepare(); ?>
        <?php echo $this->form()->openTag($this->form); ?>
        <?php echo $this->formRow($this->form->get('usuario')); ?>
        <?php echo $this->formRow($this->form->get('senha')); ?><br><br/>
        <?php echo $this->formSubmit($this->form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>

